export const REMOVE_COUNTRY = 'COUNTRYPAGE/REMOVE_COUNTRY'
export const REQUEST_COUNTRY = 'COUNTRYPAGE/REQUEST_COUNTRY'
export const RECEIVE_COUNTRY = 'COUNTRYPAGE/RECEIVE_COUNTRY'
export const INVALIDATE_COUNTRY = 'COUNTRYPAGE/INVALIDATE_COUNTRY'
